### ISSUE TITLE
Is linux userspace log path really   ~/.local/state 

### ISSUE THREAD

**Issue by dkebler** [sindresorhus/env-paths#10]
Hmmm...

At least on Ubuntu there is no `~/.local/state`  directory by default so if I try to use `envPaths(opts.appName || opts.name || 'default').log)`

I get an error cause it can't write to a non-existent directory.

Not that I or the end user can't make that directory or that I won't now check to see if it exists first and make it before the error is thrown (`make-dir` to rescue!)

but I have two comments.
1)  I can't find anywhere that states that ~/.local/state is an agreed upon location for userspace logs in Linux.  I'm not opposed to this just can't find any justification for it.  And why the cryptic `state` instead of `log`??
2)  More typically they should probably go in shared `var/log/<appname>` space with appropriate permissions. Obviously there are permission issues here but at least one would get the typical applications log path from which to proceed (at least for Linux)

still wondering if making missing directories is within the purview of this package???  Maybe with extra option `mkdir:true` which is false by default so it won't be done unless the dev really wanted it so.

**Comment by sindresorhus** [comment]
1. https://wiki.debian.org/XDGBaseDirectorySpecification#state It's not official (yet), but I don't really care. It's a good idea and better than the alternatives.
2. Intentional, yes. I didn't want the permission nightmare. I've dealt with that in the past on other modules and wanted to stay away from it this time.

---

> still wondering if making missing directories is within the purview of this package??? Maybe with extra option mkdir:true which is false by default so it won't be done unless the dev really wanted it so.

Yeah. Makes sense. Could be an option that is `true` by default. Can't remember why I didn't do this initially. I think it should be called: `{createDirectories: true}`.

**Comment by dkebler** [comment]
I already added make-dir and that works for me for now.

But if latest `fs.makdirSync` does recursive then yea better than having a non-native dependency (even yours).   

In my case I am doing this in a constructor so had to use sync version and try/catch  

So thumbs up on `{createDirectories:true}`

also readme.md for `paths.log` part should either have the link you gave or excerpt of pertinent part just because it's not "official" yet.   

FYI for fresh install of linux mint 19.3/ubuntu 18.04 `~./local/state` is not being made for new users.  Maybe it will be so in ubuntu 19+?

---------------

_side note:_ when I see some stackoverflow post asking something basic covered by your library I link them there in a comment https://npms.io/search?q=author%3Asindresorhus.  I find npms.io the best way to search within your packages and it's a prominent bookmark on my toobar!  So glad you are supported now in your work.  I thankfully use many of your packages which have saved me (and I am sure others) innumerable hours. They turn out to be a good learning resource as well.

**Comment by Siilwyn** [comment]
I wouldn't like this package to write to the filesystem to be honest. The simpleness and focused goal of *retrieving* paths should be all.

When using this package and writing to the filesystem you would need to account for writing errors either way.

**Comment by dkebler** [comment]
seems linux may be the only one where the default log directory will likely not be made.  @Siilwyn is right that is package as is does not write which is likely is better.   Maybe a clear warning about this issue just needs to be put in the readme along with a suggestion of a remedy.  Without attention this issue will break logging on linux machines until the directory is made.  @sindresorhus' suggestion to have making off by default means by default it would be a read only package.  You'd have to deliberately turn that on.  So it's @sindresorhus' call.  I have dealt with by creating this directory if need be (and in my case for every deployment to a linux box it "need be").

**Comment by sindresorhus** [comment]
I decided to go with just documentation. Thanks for the input.
