### ISSUE TITLE
Document default locations on supported operating systems?

### ISSUE THREAD

**Issue by borekb** [sindresorhus/env-paths#15]
The `conf` package points to https://github.com/sindresorhus/env-paths#pathsconfig to document where the files are stored but the section [doesn't currently contain any useful info](https://github.com/sindresorhus/env-paths/blob/de22adb240117c7aacf0365187472907a9e06872/readme.md#pathsconfig).

I know that [the truth is in the source code](https://github.com/sindresorhus/env-paths/blob/de22adb240117c7aacf0365187472907a9e06872/index.js#L9-L47) but maybe it would be useful to document this in the README as well? What do you think?

**Comment by sindresorhus** [comment]
Good idea 👍🏻

**Comment by borekb** [comment]
Just opened a PR: #16.
