### ISSUE TITLE
envPaths('app').temp get its wrong, suggests nonexistent parent dir 

### ISSUE THREAD

**Issue by fatmalama** [sindresorhus/env-paths#18]
it suggests `/tmp/$USER/app-nodejs`, but /tmp/${USER} doesn't exist on openSUSE nor Fedora and `$XDG_RUNTIME_DIR` would be more appropriately the user specific temp dir and should be defined by now on pretty much all Linux distros

**Comment by sindresorhus** [comment]
> it suggests /tmp/$USER/app-nodejs, but /tmp/${USER} doesn't exist on openSUSE nor Fedora

I don't think it exists on any Linux distribution. This package does not guarantee the directory exists. It standardises on good places to store stuff cross-platform. The username is included in the path for uniqueness.

> Applications should use this directory for communication and synchronization purposes and **should not place larger files in it**, since it might reside in runtime memory and cannot necessarily be swapped out to disk.
> - https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

This is problematic as you can put any sized files in a normal temporary directory.
