### ISSUE TITLE
browser-external:node:os:9 Module "node:os" has been externalized for browser compatibility. Cannot access "node:os.homedir" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

### ISSUE THREAD

**Issue by Meguais** [sindresorhus/env-paths#19]
i get this error i cant fix can u help me 
![image](https://user-images.githubusercontent.com/47488328/226188281-6eeecfe0-0f07-4dd5-9468-2e9341fc0cf5.png)

**Comment by Meguais** [comment]
import envPaths from 'env-paths';
const paths = envPaths('MyApp');
console.log(paths)

**Comment by sindresorhus** [comment]
This package is for Node.js, not the browser.

**Comment by Meguais** [comment]
I was going to use it for electron I want to show the main directory where I installed the program, but I could not

**Comment by Meguais** [comment]
Is there an alternative solution for electron ?
i try app.getPath() but still get this error 
there is one different node:os does not write path.join writes
