### ISSUE TITLE
make the -nodejs suffix configureable

### ISSUE THREAD

**Issue by zeke** [sindresorhus/env-paths#2]
I need a tool just like this for use on an electron project, but the `-nodejs` suffix will get in the way.

I could just `replace()` the output, but an option to specify the suffix in this lib would be nice.

**Comment by sindresorhus** [comment]
Are you aware Electron already exposes paths through `app.getPath()`?

**Comment by zeke** [comment]
Yes. I want to access these directories outside of an electron process.

**Comment by sindresorhus** [comment]
Sure, PR welcome. The suffix is there to ensure Node.js modules will never conflict with native apps of the same name. Having an option would be a good way to make that clear too.
