### ISSUE TITLE
Prefer XDG_* on all systems

### ISSUE THREAD

**Issue by uncenter** [sindresorhus/env-paths#20]
If a user explicitly defines an XDG_* environment variable on macOS or Windows, we should use those XDG_* dirs. It could also be an option, disabled by default?

**Comment by uncenter** [comment]
It could just be something like this:
```js
const xdg = name => {
    const result = {};

    if (env.XDG_DATA_HOME) {
      result.data = path.join(env.XDG_DATA_HOME, name);
    }

    if (env.XDG_CONFIG_HOME) {
      result.config = path.join(env.XDG_CONFIG_HOME, name);
    }

    if (env.XDG_CACHE_HOME) {
      result.cache = path.join(env.XDG_CACHE_HOME, name);
    }

    if (env.XDG_STATE_HOME) {
      result.log = path.join(env.XDG_STATE_HOME, name);
    }

    return result;
};
```

```js
if (process.platform === 'darwin') {
	return { ...macos(name), ...xdg(name) };
}

if (process.platform === 'win32') {
	return { ...windows(name), ...xdg(name) };
}
```

**Comment by sindresorhus** [comment]
It could maybe make sense on Windows, since Windows does not have a strong convention for all kinds of directories. On macOS, however, we should prefer following the conventions. This is important and certain folders like cache and temp are cleaned by the system, while it would not do that for XDG.

**Comment by uncenter** [comment]
> It could maybe make sense on Windows, since Windows does not have a strong convention for all kinds of directories. On macOS, however, we should prefer following the conventions. This is important and certain folders like cache and temp are cleaned by the system, while it would not do that for XDG.

But the user explicitly set those variables to those locations for a reason because they want applications to respect that. It might not be in the users best interest but that isn't the point of this package. FYI, I excluded temp from the `xdg` function because there isn't a convention for it as far as I know, so we are just talking about the cache folder here.

**Comment by sindresorhus** [comment]
On macOS, users may have accidentally set it because they share Bash config with their Linux computer. Or they may not realize the downsides with setting it. The point of this package is to provide the most appropriate locations. XDG is not a concept on macOS and neither should it be.

**Comment by uncenter** [comment]
> On macOS, users may have accidentally set it because they share Bash config with their Linux computer. Or they may not realize the downsides with setting it. The point of this package is to provide the most appropriate locations. XDG is not a concept on macOS and neither should it be.

You can disagree but people specifically *do* use it on macOS and you should respect their choices.
