### ISSUE TITLE
Incorrect paths on Linux

### ISSUE THREAD

**Issue by thesbros** [sindresorhus/env-paths#5]
If e.g. `$XDG_CACHE_HOME` is set, it will return `XDG_CACHE_HOME` instead of `XDG_CACHE_HOME/{name}` — [as seen here.](https://github.com/sindresorhus/env-paths/blob/master/index.js#L40)

Is this intended, and if not would you accept a PR to fix this?

**Comment by sindresorhus** [comment]
Ugh, yeah, that's a silly bug. PR more than welcome :)
