### ISSUE TITLE
On Windows, config should go into `env.AppData`

### ISSUE THREAD

**Issue by MicahZoltu** [sindresorhus/env-paths#8]
`%AppData%` on windows rooms across the network/domain and is more likely to be backed up.  For configuration (small user specific files managed by the application), this should go into AppData.

`%LocalAppData%` is per machine (not synced across network on login/logout), and so cache, program data, and logs are correct to go in there.

**Comment by sindresorhus** [comment]
Can you link to a source about this?

**Comment by MicahZoltu** [comment]
Here are a handful of sources, unfortunately not all of them are particularly easy reads.  I have included them here in the order that _I_ would recommend skimming over them to get the answers you seek, though if you have a bunch of time you could try to digest them all.  :)

https://msdn.microsoft.com/en-us/library/windows/desktop/bb762494(v=vs.85).aspx
https://github.com/Microsoft/vscode/issues/3884
https://superuser.com/a/632899/401511
https://msdn.microsoft.com/en-us/library/windows/apps/hh465094.aspx
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-vista/cc766489(v=ws.10)
